### ISSUE TITLE
[FEAT] Plans

### ISSUE THREAD

**Issue by MorganeLecurieux** [getlago/lago-front#16]
# TODO
- [x] Add warning modal on create billable metrics flow quit button
- [x] Add Plans in main nav

## List
- [x] Loading state
- [x] Error state
- [x] Empty state
- [x] Item with Plan name / Plan code / Nb of customers / Nb of charges / Creation date
- [x] Header width Plan name / Plan code / Nb of customers / Nb of charges / Creation date
- [x] Responsive (hide Nb of customers / Nb of charges)

## Creation page
- [x] Code snippet (fixed)
- [x] Responsive
- [ ] Button is disabled until all required field are filled
- [x] On click on leave, there is a warning modal with cancel and proceed
- [x] Success page
### Section basic infos
- [x] Name is focused by default
### Section plan model
- [x] Click on `Monthly` --> Beginning of the month, End of the month, Subscription date
- [x] Click on `Yearly` --> Beginning of the year, End of the year, Subscription date
- [x] Deal with the `EUR` currency and `USD`
- [x] VAT is set to 0 by default
- [x] Pro-rata is optional
### Section additional charges
- [x] On "add a charge" open a modal
- [x] Combobox load billable metrics (loading state in the combobox)
- [x] Combobox empty state 
- [x] A charge is added --> displayed in the list
- [x] Charge can be expended/collapsed
- [x] By default the charge is expanded
- [ ] A charge can be deleted
- [x] Tooltip on the delete button
- [x] Tooltip on the expand button
- [ ] By default, charge model is `standard pricing` (only option for now)
- [ ] Currency of the charge is same as in the plan and is disabled
- [ ] charge frequency is set to `recurring` by default
- [ ] Tooltip of the frequency adapt to the value
- [ ] VAT is optional and set to 0 by default
