### ISSUE TITLE
[BUG] Customer cache and fragment management

### ISSUE THREAD

**Issue by ansmonjol** [getlago/lago-front#865]
## Context

This ticket has a wide scope.

It all start with an Apollo warning about cache management

![image](https://user-images.githubusercontent.com/5517077/222179013-264c6b6a-44f3-4f67-8e50-a11095dcb875.png)

It happen when we udpate a customer metadata and remove one in the list.

Going further, it appear that the fragment management is messy, and that we manually udpate the cache, which we should not.

Basically, warning occurs because Apollo does not know what to do with the old metada list having more items that the received one.

This warning have been spotted during customer metadata and patched with a cache definition for customerMetadata

## Steps to reproduce

**You need to have a customer with one or more metadata**
**You need to remove the `customerMetadata` key in `src/core/apolloClient/cache.ts`**

- Edit customer infos
- Delete one metadata
- Save customer
-> A warning should be prompted in your console

## Work breakdown

- [x] Get rid of models `single_object` types on BE side
- [x] make sure the BE change is impacted on FE fragments definition
- [x] Refactor FE fragment definition and data management in the customer details and customer add/edit drawer
- [ ] Remove `customerMetadata` key in `src/core/apolloClient/cache.ts`, remove manual cache update and make sure the warning is not present anymore when removing a metadata from an existing customer
